name: ml4h

channels:
- conda-forge
- defaults

dependencies:
  - python=3.9
  - pip
  - scikit-learn
  - numpy
  - matplotlib
  - seaborn
  - ipykernel
  - pandas
  - pip:
    - pytorch-lightning==1.6.0