name: ml4h

channels:
- conda-forge
- defaults

dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - seaborn
  - ipykernel
  - pandas
  - scikit-learn
  - pytorch-lightning
  - torchmetrics
  - tensorboard
  - tensorflow